apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: iceicebabyaf/test-repo-app:latest
        command: ["/bin/sh", "-c"]
        args: ["/app/build/testproj --logtostderr && sleep infinity"]