apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: web-service-log-binding
subjects:
- kind: ServiceAccount
  name: web-service-account
  namespace: default
roleRef:
  kind: Role
  name: web-service-log-role
  apiGroup: rbac.authorization.k8s.io