apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: {{ .Values.web.name }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
      annotations:
        # Добавляем аннотацию, которая меняется при каждом helm upgrade
        checksum/app-image: "{{ .Values.app.tag | sha256sum }}"
    spec:
      serviceAccountName: web-service-account
      containers:
      - name: {{ .Values.web.name }}
        image: {{ .Values.web.image }}:{{ .Values.web.tag }}
        imagePullPolicy: Always
        command: ["/entrypoint.sh"]