name: Docker Build & Push

on:
  push:
    branches:
      - main
      - feature/docker-web-hub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-repo-app:latest -f Dockerfile.app .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-repo-web:latest -f Dockerfile.web .

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-repo-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-repo-web:latest
