name: Docker Web Tests CI/CD

on:
  push:
    branches:
      - main
      - feature/k8s-helm
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push test-app image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.app
        push: true
        tags: iceicebabyaf/test-repo-app:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        no-cache: true

    - name: Build and push test-web image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.web
        push: true
        tags: iceicebabyaf/test-repo-web:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        no-cache: true

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.2

    - name: Package Helm chart
      run: |
        helm package helm/test-repo-chart
        mv test-repo-chart-*.tgz test-repo-chart.tgz

    - name: Publish Helm chart to GitHub Releases
      uses: softprops/action-gh-release@v0.1.15
      if: github.event_name == 'push' && github.ref == 'refs/heads/feature/k8s-helm'
      with:
        files: test-repo-chart.tgz
        tag_name: v${{ github.run_number }}-${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

